config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/welcome/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get '/orders/add_list', to: '/orders#add_list'

  resources :items
  resources :customers
  resources :orders
  resources :lists
  resources :purchases
  resources :suppliers
  resources :users

  root 'welcome#index'
end

app/models/customer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: customers
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  email          :string           not null
#  address        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Customer < ApplicationRecord
  validates :name, presence: true

  has_many :orders
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @customers = Customer.all.order(:id)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to customers_path
    else
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customers_path
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :address)
  end
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true) do |form| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %>
        Saveできませんでした:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label "Customer Name" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label "E-Mail" %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label "Shipping Address" %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </p>
<% end %>
<%= link_to "Back", customers_path %>

app/views/customers/edit.html.erb
<h1>[Edit] <%= @customer.name %></h1>
<%= render 'form' %>

app/views/customers/index.html.erb
<div class="row add-button">
  <%= link_to "Add New Customer", new_customer_path, class: "btn btn-primary" %>
</div>
<div class="row">
  <table class="table table-sm table-hover">
    <thead class="thead-dark">
      <th>#</th>
      <th>Customer Name</th>
      <th>E-Mail</th>
      <th>Shipping Address</th>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, edit_customer_path(customer.id) %></td>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.address %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/new.html.erb
<h1>Add New Customer</h1>
<%= render 'form' %>