config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/welcome/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get '/orders/add_list', to: '/orders#add_list'

  resources :items
  resources :customers
  resources :orders
  resources :lists
  resources :purchases
  resources :suppliers
  resources :users

  root 'welcome#index'
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  order_number   :integer          not null
#  customer_id    :integer          not null
#  gst            :float
#  pst            :float
#  total          :float
#  order_date     :date             not null
#  payment_date   :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Order < ApplicationRecord
  validates :order_number, presence: true
  validates :order_date, presence: true

  belongs_to :customer, optional: true
  has_many :lists, inverse_of: :order, dependent: :destroy

  accepts_nested_attributes_for :lists, reject_if: :all_blank, allow_destroy: true

  def selectable_customers
    Customer.all.order(:id)
  end

  def self.total_sales
    orders = Order.all
    sum = 0
    orders.each do |order|
      sum += order.total_price
    end
    sum
  end

  def total_price
    lists.to_a.sum { |list| list.subtotal }
  end

  private

    def self.set_order_number
      if Order.last
        new_number = Order.last.order_number + 1
      else
        new_number =3001
      end
      new_number
    end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: [:edit, :update]
  before_action :exchange_rate, only: [:new, :show]

  def index
    @orders = Order.includes([:lists ,:customer]).order(order_number: 'DESC')
    @total_sales = Order.includes([:customer, lists: :item]).total_sales
    @total_purchase = Purchase.total_purchase
    @profit = BigDecimal(@total_sales.to_s) - BigDecimal(@total_purchase.to_s)
  end

  def show
    @order = Order.find(params[:id])
    @lists = List.where(order_id: @order.id)
    @total = @order.total
  end

  def new
    @order = Order.new
    @order.order_number = Order.set_order_number
    ActiveRecord::Base.connection.execute("SELECT setval('lists_id_seq', coalesce((SELECT MAX(id)+1 FROM lists), 1), false)")
    @order.lists.build
  end

  def create
    @order = Order.new(order_params)
    @order.total = @order.total_price

    if @order.save
      redirect_to orders_path, notice: 'The order has been created.'
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.total = @order.total_price
    if @order.update(order_params) && @order.update(total: @order.total_price)
      redirect_to orders_path, notice: 'The order has been updated.'
    else
      render :edit
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to orders_path
    else
      render :show
    end
  end

  def add_list
    @list = @order.lists.build
  end

  def exchange_rate
    exchange_rates = Exchange.last(2)
    rate = (exchange_rates[1].rate / exchange_rates[0].rate).round(2)
    timestamp = exchange_rates[1].created_at.strftime("%d/%b/%Y %I:%M %p")
    @exchange_rate = "#{rate} ( #{timestamp} )"
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params
        .require(:order)
        .permit(:order_number, :customer_id, :order_date, :payment_date, :gst, :pst, :total,
          lists_attributes: [:id, :order_id, :item_id, :amount, :list_price, :discount, :_destroy])
    end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: @order, local: true) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %>
        以下のエラーによりSaveできませんでした:
      </h2>
      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <%= f.label "Order Number" %><br>
      <%= f.number_field :order_number, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, f.object.selectable_customers, :id, :name, {}, class: 'form-control custom-select' %>
    </div>

    <div class="col-md-3">
      <%= f.label "Order Date" %><br>
      <%= f.date_field :order_date, class: 'form-control' %>
    </div>

    <div class="col-md-3">
      <%= f.label "Payment Date" %><br>
      <%= f.date_field :payment_date, class: 'form-control' %>
    </div>
  </div>

  <div class="row list-item-nested-form">
    <h3>Line Items</h3>
    <%= link_to_add_association "Add Item", f, :lists, class: "btn btn-primary add-list",
        data: {
          association_insertion_node: '#list-association',
          association_insertion_method: 'append'}
    %>
    <table class="table table-sm table-hover orderTableHeader">
      <thead>
        <th>Item</th>
        <th>Quantity</th>
        <th>Discount</th>
        <th></th>
      </thead>
      <tbody id='list-association'>
        <div class='form-group'>
          <%= f.fields_for :lists do |l| %>
            <%= render 'list_fields', f: l %>
          <% end %>
        </div>
      </tbody>
    </table>
  </div>
  <div>
    <%= f.submit "Save", class: "form-control btn btn-primary" %>
    <%= link_to "Back", orders_path %>
  </div>
<% end %>

app/views/orders/_list_fields.html.erb
<tr class='nested-fields'>
  <%= f.hidden_field :order_id, :value => @order.id %>
  <td>
    <%= f.collection_select :item_id, f.object.selectable_items, :id, :name, {}, class: 'form-control custom-select' %>
  </td>
  <td>
    <%= f.text_field :amount, class: 'form-control' %>
  </td>
  <td>
    <%= f.text_field :discount, class: 'form-control' %>
  </td>
  <td>
    <%= link_to_remove_association 'x', f, class: 'btn btn-default' %>
  </td>
</tr>

app/views/orders/edit.html.erb
<h1>[Edit] Order#: <%= @order.order_number %></h1>
<%= render 'form' %>

app/views/orders/index.html.erb
<div class="row orderTableHeader">
  <div class="col-sm-3 add-button">
    <%= link_to "Add New Order", new_order_path, class: "btn btn-primary" %>
  </div>
  <div class="col-sm-3">
    <p>Sales<span>$<%= @total_sales %></span></p>
  </div>
  <div class="col-sm-3">
    <p>Purchase<span class="red">$<%= @total_purchase %></span></p>
  </div>
  <div class="col-sm-3">
    <p>Profit<span class="<%= 'red' if @profit < 0 %>">$<%= @profit %></span></p>
  </div>
</div>

<div class="row">
  <table class="table table-hover">
    <thead class="thead-dark">
      <th>Order Number</th>
      <th>Customer</th>
      <th>Order Date</th>
      <th>Payment Date</th>
      <th>Total</th>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= link_to order.order_number, edit_order_path(order.id) %></td>
        <% begin %>
        <td><%= order.customer.name %></td>
        <% rescue %>
        <td></td>
        <% end %>
        <td><%= order.order_date %></td>
        <td><%= order.payment_date %></td>
        <td><%= order.total %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order , path: orders_path, method: :post %>

app/views/orders/show.html.erb
<%= form_with(model: @order, local: true) do |f| %>
  <div class="row">
    <div class="col-md-2">
      <%= f.label "Order Number" %><br>
      <%= f.number_field :order_number, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= f.label "Customer" %><br>
      <%= f.collection_select :customer_id, f.object.selectable_customers, :id, :name, {}, class: 'form-control custom-select' %>
    </div>

    <div class="col-md-3">
      <%= f.label "Order Date" %><br>
      <%= f.date_field :order_date, class: 'form-control' %>
    </div>

    <div class="col-md-3">
      <%= f.label "Payment Date" %><br>
      <%= f.date_field :payment_date, class: 'form-control' %>
    </div>
  </div>
  <hr>

<% end %>

  <div class="row order-list-items">
    <%= link_to "Add New List", new_list_path(order_id: @order.id), class: "btn btn-primary" %>
    <table class="table table-sm table-hover">
      <thead>
        <th>Item</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Discount</th>
        <th>Sub Total</th>
      </thead>
      <tbody>
        <% @lists.each do |li| %>
        <tr>
          <td><%= li.item.name %></td>
          <td><%= li.list_price %></td>
          <td><%= li.amount %></td>
          <td><%= li.discount %></td>
          <td><%= li.subtotal %></td>
        </tr>
        <% end %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><span class="bold"><%= @total %></span></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div>
    <button class="btn btn-danger"><%= link_to 'Delete', "/orders/#{@order.id}", method: :delete, data: {confirm: "Are you sure to delete this order?"} %></button>
  </div>
</div>