config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/welcome/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get '/orders/add_list', to: '/orders#add_list'

  resources :items
  resources :customers
  resources :orders
  resources :lists
  resources :purchases
  resources :suppliers
  resources :users

  root 'welcome#index'
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  price          :integer          not null
#  stock          :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true

  has_many :lists
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :stock)
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: @item, local: true) do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %>
        Saveできませんでした:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label "Item Name" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label "Price" %><br>
    <%= form.number_field :price %>
  </p>

  <p>
    <%= form.label "Stock" %><br>
    <%= form.number_field :stock %>
  </p>

  <p>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </p>
<% end %>
<%= link_to "Back", items_path %>

app/views/items/edit.html.erb
<h1>[Edit] <%= @item.name %></h1>
<%= render 'form' %>

app/views/items/index.html.erb
<div class="row add-button">
  <%= link_to "Add New Item", new_item_path, class: "btn btn-primary" %>
</div>
<div class="row">
  <table class="table table-sm table-hover">
    <thead class="thead-dark">
      <th>#</th>
      <th>Item Name</th>
      <th>Price</th>
      <th>Stock</th>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, edit_item_path(item.id) %></td>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.stock %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/new.html.erb
<h1>Add New Item</h1>
<%= render 'form' %>