config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/welcome/index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #get '/orders/add_list', to: '/orders#add_list'

  resources :items
  resources :customers
  resources :orders
  resources :lists
  resources :purchases
  resources :suppliers
  resources :users

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: customers
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  email          :string           not null
#  address        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Customer < ApplicationRecord
  validates :name, presence: true

  has_many :orders
end

app/models/exchange.rb
class Exchange < ApplicationRecord
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  price          :integer          not null
#  stock          :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :stock, presence: true

  has_many :lists
end

app/models/line.rb
class Line < ApplicationRecord
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  belongs_to :purchase

  def subtotal
    price * quantity - discount
  end
end

app/models/list.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: lists
#
#  id             :integer          not null, primary key
#  order_id       :integer          not null
#  item_id        :integer          not null
#  amount         :integer          not null
#  list_price     :integer
#  discount       :integer          default: 0
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class List < ApplicationRecord
  validates :item_id, presence: true
  validate do |list|
    list.errors.add(:item_id, :blank, message: 'cannot be blank') if list.item_id.nil?
  end
  validates :amount, presence: true, numericality: { greater_than: 0 }

  belongs_to :order
  belongs_to :item

  def subtotal
    item.price * amount - discount
  end

  def selectable_items
    Item.all
  end
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  order_number   :integer          not null
#  customer_id    :integer          not null
#  gst            :float
#  pst            :float
#  total          :float
#  order_date     :date             not null
#  payment_date   :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Order < ApplicationRecord
  validates :order_number, presence: true
  validates :order_date, presence: true

  belongs_to :customer, optional: true
  has_many :lists, inverse_of: :order, dependent: :destroy

  accepts_nested_attributes_for :lists, reject_if: :all_blank, allow_destroy: true

  def selectable_customers
    Customer.all.order(:id)
  end

  def self.total_sales
    orders = Order.all
    sum = 0
    orders.each do |order|
      sum += order.total_price
    end
    sum
  end

  def total_price
    lists.to_a.sum { |list| list.subtotal }
  end

  private

    def self.set_order_number
      if Order.last
        new_number = Order.last.order_number + 1
      else
        new_number =3001
      end
      new_number
    end
end

app/models/purchase.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: purchases
#
#  id             :integer          not null, primary key
#  supplier_id    :integer          not null
#  item_name      :string           not null
#  amount         :integer          not null
#  price          :float            not null
#  cad            :float
#  jpy            :integer
#  payment_method :string           not null
#  note           :text
#  order_date     :date             not null
#  payment_date   :date
#  exchangerate   :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Purchase < ApplicationRecord
  validates :order_date, presence: true

  belongs_to :supplier
  has_many :lines

  accepts_nested_attributes_for :lines, reject_if: :all_blank, allow_destroy: true

  def self.total_purchase
    sum(:price)
  end
end

app/models/supplier.rb
# frozen_string_literal: true

# Table name: suppliers
#
#  id             :integer          not null, primary key
#  name           :string           not null
#  representative :string           not null
#  email          :string           not null
#  address        :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Supplier < ApplicationRecord
  validates :name, presence: true
  validates :representative, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :purchases
end

app/models/user.rb
# frozen_string_literal: true

# Table name: users
#
#  id               :integer          not null, primary key
#  name             :string           not null
#  email            :string           not null
#  password_digest  :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# index_users_on_email (email) UNIQUE
#

class User < ApplicationRecord
  # Not all of the databases use index for distinguishing upper cases and lower cases.
  # So cast email address to downcase before save it
  before_save { self.email = email.downcase }

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :stock)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_nav_item(item)
    url = request.url

    return ' active active-underscore' if url.include?(item)
  end
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/listitems_helper.rb
# frozen_string_literal: true

module ListitemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/purchases_helper.rb
# frozen_string_literal: true

module PurchasesHelper
  def unpaid(payment_date)
    return 'unpaid' if payment_date.nil?
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SDL2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">SDL2</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if logged_in? %>
          <li class="nav-item<%= active_nav_item("orders") %>">
            <%= link_to "Orders", orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item<%= active_nav_item("purchases") %>">
            <%= link_to "Purchases", purchases_path, class: "nav-link" %>
          </li>
          <li class="nav-item<%= active_nav_item("items") %>">
            <%= link_to "Item Master", items_path, class: "nav-link" %>
          </li>
          <li class="nav-item<%= active_nav_item("customers") %>">
            <%= link_to "Customer Master", customers_path, class: "nav-link" %>
          </li>
          <li class="nav-item<%= active_nav_item("suppliers") %>">
            <%= link_to "Supplier Master", suppliers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown my-2 my-lg-0">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account <b class="caret"></b>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", '#', class: "dropdown-item" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
        <span class="navbar-text">
          <strong><%= @exchange_rate %></strong>
        </span>

      </div>
    </nav>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container main-contents">
      <%= yield %>
    </div>

    <footer>
      <p>SDL2</p>
    </footer>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>